spring:
  application:
    name: book-store
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    url: jdbc:postgresql://c-bookstore.64u26ppta3q332.postgres.cosmos.azure.com:5432/bookstore?sslmode=require
    username: citus
    password: Vanshu@fb4
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    # database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080

